<?php 
session_start();
require_once 'config.php';

// Ensure all necessary session data is available
if (!isset($_SESSION['vehicle']) || !isset($_SESSION['passenger_name']) || !isset($_SESSION['vehicle_id'])) {
    // Redirect back to step 3 if booking data is incomplete
    header('Location: step3.php');
    exit;
}

// Calculate total price including optional services
$total_price = $_SESSION['vehicle']['price'];
if (isset($_SESSION['tourist_guide']) && $_SESSION['tourist_guide'] == 'yes') {
    $total_price += 100; // Tourist Guide fee
}
if (isset($_SESSION['luggage_assistance']) && $_SESSION['luggage_assistance'] == 'yes') {
    $total_price += 50; // Luggage Assistance fee
}

$formatted_price = number_format($total_price, 2);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Step 4 - QR Payment - Global Sunrise Travel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Shared Styles (Matching step3.php) */
        body { background-color: #f8f9fa; }
        .container { max-width: 900px; }
        .navbar { background-color: #003366 !important; }
        .text-primary { color: #003366 !important; }
        .btn-primary { background-color: #003366; border-color: #003366; }
        .btn-primary:hover { background-color: #002147; border-color: #002147; }
        .footer { background-color: #003366; color: #f8f9fa; padding: 20px 0; margin-top: 50px; }
        .footer a { color: #ffd700 !important; text-decoration: none; }
        .footer a:hover { color: #fff !important; }
        
        /* Step Progress Styling (Updated for Step 4 Active) */
        .step-progress { background: white; padding: 20px; border-radius: 10px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); border: 1px solid #eee; }
        .step-item.completed .step-number { background-color: #ffd700 !important; color: #003366 !important; font-weight: bold; }
        
        /* QR Specific Styles */
        .qr-card {
            background-color: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 6px 12px rgba(0,0,0,0.15);
            text-align: center;
            border-top: 5px solid #003366;
        }
        .qr-code {
            width: 200px;
            height: 200px;
            margin: 20px auto;
            /* Placeholder for the actual QR image (e.g., generated by a library) */
            background-color: #e0e0e0; 
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            color: #333;
            border: 5px solid #003366;
            border-radius: 8px;
        }
        .instruction-list {
            text-align: left;
            margin-top: 20px;
        }
    </style>
</head>
<body>

    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="logo.png" alt="Logo" class="d-inline-block align-text-top me-2" width="100">
                Global Sunrise Travel
            </a>
        </div>
    </nav>

    <div class="container mt-4">
        <!-- Step Progress -->
        <div class="step-progress">
            <div class="row text-center">
                <div class="col-md-3">
                    <div class="step-item completed">
                        <div class="step-number rounded-circle d-inline-flex align-items-center justify-content-center"
                             style="width: 30px; height: 30px; background-color: #ffd700 !important; color: #003366 !important; font-weight: bold;">✓</div>
                        <div class="step-label mt-1 text-muted">Trip Details</div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="step-item completed">
                        <div class="step-number rounded-circle d-inline-flex align-items-center justify-content-center"
                             style="width: 30px; height: 30px; background-color: #ffd700 !important; color: #003366 !important; font-weight: bold;">✓</div>
                        <div class="step-label mt-1 text-muted">Select Vehicle</div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="step-item completed">
                        <div class="step-number rounded-circle d-inline-flex align-items-center justify-content-center"
                             style="width: 30px; height: 30px; background-color: #ffd700 !important; color: #003366 !important; font-weight: bold;">✓</div>
                        <div class="step-label mt-1 text-muted">Passenger Details</div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="step-item active">
                        <div class="step-number bg-primary text-white rounded-circle d-inline-flex align-items-center justify-content-center"
                             style="width: 30px; height: 30px; background-color: #003366 !important;">4</div>
                        <div class="step-label mt-1 fw-bold text-primary">Confirmation</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="qr-card">
            <h2 class="text-primary mb-4">Complete Your Payment</h2>
            
            <p class="lead">Please scan the QR code below using your bank app to complete the payment of <strong>RM <?php echo $formatted_price; ?></strong>.</p>
            
            <div class="qr-code">
                [QR Code Placeholder]
            </div>

            <div class="instruction-list">
                <h5 class="text-primary mt-4 mb-3">Payment Instructions:</h5>
                <ol>
                    <li>Open your preferred Malaysian banking app (e.g., Maybank, CIMB, Public Bank).</li>
                    <li>Select the 'Scan & Pay' or 'DuitNow QR' option.</li>
                    <li>Scan the QR code displayed above.</li>
                    <li>Verify the amount is **RM <?php echo $formatted_price; ?>** and the recipient is **GLOBAL SUNRISE TRAVEL**.</li>
                    <li>Complete the transaction.</li>
                    <li>**IMPORTANT**: Once the payment is successful, click the button below to confirm your booking and receive your itinerary.</li>
                </ol>
            </div>
            
            <!-- MODIFIED: Changed link to form submission to trigger the final backend logic -->
            <form action="process_confirmation.php" method="POST">
                <input type="hidden" name="total_price" value="<?php echo $total_price; ?>">
                <!-- Send a flag indicating payment method used -->
                <input type="hidden" name="payment_method" value="QR Code/DuitNow">
                
                <button type="submit" class="btn btn-primary btn-lg mt-4 w-75">
                    I have paid. Proceed to Booking Confirmation
                </button>
            </form>
        </div>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container text-center">
            <p>&copy; 2025 Global Sunrise Travel & Tours. All Rights Reserved.</p>
            <p>
                <a href="contact.php" class="text-white me-3">Contact</a> |
                <a href="about us.php" class="text-white mx-3">About Us</a> |
                <a href="#" class="text-white ms-3">Terms</a>
            </p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
